name: "Tests"
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: cachix/install-nix-action@v14
        with:
          nix_path: nixpkgs=channel:nixpkgs-unstable
          install_url: https://releases.nixos.org/nix/nix-2.3.16/install
      - uses: cachix/cachix-action@v10
        with:
          name: npmlock2nix
          signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
      - run: nix-shell --run "nixpkgs-fmt --check ."
      - run: ./test.sh
